#!/bin/sh
set -e

# Source app env variables
. /app/.env
if [ -f /app/.env.local ]; then
  . /app/.env.local
fi

# Ensure the app's dependencies are installed
echo "Installing dependencies..."
bundle check || bundle install

export PGPASSWORD="$DATABASE_PASSWORD"

# Wait for Postgres to become available.
echo "Checking for Postgres..."
until psql -h "$DATABASE_HOST" -U "$DATABASE_USERNAME" -c '\q' 2>/dev/null; do
  echo >&2 "Postgres is unavailable - sleeping"
  sleep 1
done
echo "Postgres is available: continuing with database setup..."

# Database setup
if psql -h "$DATABASE_HOST" -U "$DATABASE_USERNAME" -lqt | cut -d \| -f 1 | grep -qw "$DATABASE_NAME"; then
  echo "Database $DATABASE_NAME exists"
else
  echo "Database $DATABASE_NAME doesn't exist, setting up..."
  bundle exec rails db:setup
fi

# Remove leftover pid files
rm -f tmp/pids/server.pid

# Run any command specified in docker-compose or Dockerfile
# In practice this runs bin/rs which is specified in Dockerfile
exec "$@"
